-- Add class to Course
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "class" TEXT NOT NULL DEFAULT '';

-- LiveClass
CREATE TABLE IF NOT EXISTS "LiveClass" (
  "id" TEXT NOT NULL, "title" TEXT NOT NULL, "meetUrl" TEXT NOT NULL,
  "scheduledAt" TIMESTAMP(3) NOT NULL, "duration" INTEGER NOT NULL DEFAULT 60,
  "courseId" TEXT NOT NULL, "isCompleted" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "LiveClass_pkey" PRIMARY KEY ("id")
);

-- HomeworkSubmission
CREATE TABLE IF NOT EXISTS "HomeworkSubmission" (
  "id" TEXT NOT NULL, "userId" TEXT NOT NULL, "homeworkId" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL DEFAULT '', "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "grade" INTEGER, "feedback" TEXT NOT NULL DEFAULT '',
  CONSTRAINT "HomeworkSubmission_pkey" PRIMARY KEY ("id")
);

-- Question
CREATE TABLE IF NOT EXISTS "Question" (
  "id" TEXT NOT NULL, "testId" TEXT NOT NULL, "text" TEXT NOT NULL,
  "optionA" TEXT NOT NULL, "optionB" TEXT NOT NULL, "optionC" TEXT NOT NULL, "optionD" TEXT NOT NULL,
  "correctOption" TEXT NOT NULL, "marks" INTEGER NOT NULL DEFAULT 4,
  CONSTRAINT "Question_pkey" PRIMARY KEY ("id")
);

-- TestSubmission
CREATE TABLE IF NOT EXISTS "TestSubmission" (
  "id" TEXT NOT NULL, "userId" TEXT NOT NULL, "testId" TEXT NOT NULL,
  "answers" JSONB NOT NULL, "score" INTEGER NOT NULL DEFAULT 0,
  "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TestSubmission_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "Attendance" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'present';

CREATE TABLE IF NOT EXISTS "Notification" (
  "id" TEXT NOT NULL, "userId" TEXT NOT NULL, "title" TEXT NOT NULL,
  "message" TEXT NOT NULL, "isRead" BOOLEAN NOT NULL DEFAULT false,
  "type" TEXT NOT NULL DEFAULT 'general', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "method" TEXT NOT NULL DEFAULT 'cash';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "month" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Homework" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Homework" ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Homework" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "totalMarks" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "duration" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "scheduledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "isPublished" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
